% Script: ztrack_ramp_demo1_plot_msd1.m
%
% Script to demonstrate use of NeuroSpec 2.2
% z-tracker estimate of time varying coherence over segmented data
% This script plots figures based on data generated by script: ztrack_ramp_demo1.m
%
% Copyright 2018, David M. Halliday.
% This file is part of NeuroSpec.
%
%    NeuroSpec is free software; you can redistribute it and/or modify
%    it under the terms of the GNU General Public License as published by
%    the Free Software Foundation; either version 2 of the License, or
%    (at your option) any later version.
%
%    NeuroSpec is distributed in the hope that it will be useful,
%    but WITHOUT ANY WARRANTY; without even the implied warranty of
%    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%    GNU General Public License for more details.
%
%    You should have received a copy of the GNU General Public License
%    along with NeuroSpec; if not, write to the Free Software
%    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
%
%    NeuroSpec is available at:  http://www.neurospec.org/
%    Contact:  contact@neurospec.org
%
% Reference: Halliday DM, Brittain J-S, Stevenson CW, Mason R (2018)
%  Adaptive Spectral Tracking for Coherence Estimation: The z-tracker.
%  Journal of Neural Engineering, 15(2), 026004.
%  https://doi.org/10.1088/1741-2552/aaa3b4
%
% Plotting of MSD box plots and histogram of P_l estimates

% Calculate mean over ALL frequencies for each segment size
coh_mean=cell(size(coh));
for ind_seg=1:length(seg_pwr_all)
  coh_mean{ind_seg}=squeeze(mean(coh{ind_seg})); % Mean over frequencies, first dimension
end

% Calculate target coherence for each segment size, T, at midpoints of each segment
w_mean_all=cell(length(seg_pwr_all),1);

for ind_seg=1:length(seg_pwr_all)
  [np_freq np_seg np_q np_trials]=size(coh{ind_seg});  % Sizes
  w_mean_all{ind_seg}=mean(reshape(ch_target{1}(1:seg_size_all(ind_seg)*np_seg),seg_size_all(ind_seg),np_seg))';
end

% Calculate MSD for this data: by T for each value of q
np_q_tot=length(Q_str_all);
msd_dat_mean=zeros(np_trials,np_q_tot,length(seg_pwr_all));

for ind_seg=1:length(seg_pwr_all)
  for ind_q=1:np_q_tot
    msd_dat_mean(:,ind_q,ind_seg)=zt_msd1(w_mean_all{ind_seg},squeeze(coh_mean{ind_seg}(:,ind_q,:)));
  end
end

%--------------------------------------
% Focus on T=128, MSD analysis using mean across reduced set of frequencies

% Using T=128, 1st value of T
msd_ind_seg=1;
% Using 31 frequencies covers first half of frequency range up to f_1/4, fN=f_1/2
coh_mean_ind=(1:31)';

% Mean over this reduced frequency range for single value of T=128
% coh_mean_1: [np_seg,np_q,np_trials]
[np_freq np_seg np_q np_trials]=size(coh{msd_ind_seg}(coh_mean_ind,:,:,:));
coh_mean_1=squeeze(mean(coh{msd_ind_seg}(coh_mean_ind,:,:,:)));

% Calculate MSD for reduced frequency range over trials for 8 values of alpha
msd_dat_mean_1=zeros(np_trials,np_q_tot);
for ind_q=1:np_q_tot
  msd_dat_mean_1(:,ind_q)=zt_msd1(w_mean_all{msd_ind_seg},squeeze(coh_mean_1(:,ind_q,:)));
end

% Single frequency MSD for T=128 and alpha=0.9 Smooth, 
% Frequency indices to use, increasing in octaves from lowest ~8Hz -> 250Hz
ost_freq_ind=[1 2 4 8 16 32];
[np_freq np_seg np_q np_trials]=size(coh{msd_ind_seg});
msd_dat_ost_freq=zeros(np_trials,length(ost_freq_ind));
msd_ind_q=8;  % Specify which alpha to use, alpha=0.9, smoothing.
for ind_freq=1:length(ost_freq_ind)
  msd_dat_ost_freq(:,ind_freq)=zt_msd1(w_mean_all{msd_ind_seg},squeeze(coh{msd_ind_seg}(ost_freq_ind(ind_freq),:,msd_ind_q,:)));
end


%--------------------------------------
% JNE figure 4 Boxplot - effect of T
figure
box_label=[{'T=128'},{'T=256'},{'T=512'},{'T=1024'}];
plot_ind_q=8; % Using last configuration, alpha=0.9, smoothing
boxplot(squeeze(msd_dat_mean(:,plot_ind_q,:)),'notch','on','labels',box_label,'LabelOrientation','inline','color','k','symbol','k+')
box off
title('z-tracker MSD - effect of T')

%--------------------------------------

% JNE figure 5 MSD Box plot: 8 configurations (T=128) over same no of frequencies and scales
Q_str_JNE=[{'\alpha=0.1 T'},{'\alpha=0.37 T'},{'\alpha=0.61 T'},{'\alpha=0.9 T'},{'\alpha=0.1 S'},{'\alpha=0.37 S'},{'\alpha=0.61 S'},{'\alpha=0.9 S'}];
figure
  boxplot(msd_dat_mean_1,'notch','on','labels',Q_str_JNE,'LabelOrientation','inline','color','k','symbol','k+')
  box off
  title(['MSD: z-tracker, ',num2str(tau),' sec ramp.'])
  h = findobj(gca, 'type', 'text');
  set(h, 'Interpreter', 'tex');
  set(h, 'FontName','Times');


%------------------------------------------------------------------------------
% JNE figure 6 (upper) - single freq MSD
figure
  box_label=[{'7.8 Hz'},{'15.6 Hz'},{'31.25 Hz'},{'62.5 Hz'},{'125 Hz'},{'250 Hz'},];
  boxplot(msd_dat_ost_freq,'notch','on','labels',box_label,'LabelOrientation','inline','color','k','symbol','k+')
  box off
  title(['MSD - z-tracker, single frequency'])


%------------------------------------------------------------------------------
% Extract P_l data for T=128
pk_ind_seg=1; % Using T=128
[np_freq np_seg np_q np_trials]=size(coh{pk_ind_seg});  % Sizes

% Pk data
Pk_dat_all_mean=zeros(np_trials,np_q);
Pk_dat_all_med=zeros(np_trials,np_q);

for ind_alpha=1:np_q
  for ind_trial=1:np_trials
    % Extract Pl values - select mean(Pl) OR median(Pl) for each trial
    Pk_dat_all_mean(ind_trial,ind_alpha)=mean(cl{pk_ind_seg,ind_alpha}(ind_trial).ost_P);
    Pk_dat_all_med(ind_trial,ind_alpha)=median(cl{pk_ind_seg,ind_alpha}(ind_trial).ost_P);
  end
end

% JNE figure 13, Median P_l boxplots
figure
  boxplot(Pk_dat_all_med,'notch','on','labels',Q_str_JNE,'LabelOrientation','inline','color','k','symbol','k+')
  title(['Median {\itP_l} Tau: ',num2str(tau),'. T: ',num2str(seg_size_all(pk_ind_seg)),', Trials: ',num2str(np_trials)])
  h = findobj(gca, 'type', 'text');
  set(h, 'Interpreter', 'tex');
  set(h, 'FontName','Times');


%------------------------------------------------------------------------------
% Histogram of Pk for one trial, using all L values.
Pk_dat1=zeros(np_seg,1);

ind_alpha=8; % Using alpha=0.9, smoothing
ind_trial=1; % First trial

Pk_dat=cl{pk_ind_seg,ind_alpha}(ind_trial).ost_P;


hist_max=0.14;  
figure
  [hist_n,hist_x]=hist(Pk_dat,(0:0.005:0.25));
  bar(hist_x,hist_n/sum(hist_n),1,'FaceColor',[0.5 0.5 0.5])  
  % Add line with MWT variance, K=10, This is 0.056 (NB Not 0.56 as in JNE figure legend).
  MWT_var=1/(2*(10-1));
  hold on
  plot([MWT_var MWT_var],[0 hist_max],'k--')
  hold off
  title(['{\it P_l} over segments, \alpha=0.9 S'])
  box off
  axis([0.02 0.2 0 hist_max])
  xlabel('\it P_l')
  
  