% Script: ztrack_ramp_demo1_plot1.m
%
% Script to demonstrate use of NeuroSpec 2.2
% z-tracker estimate of time varying coherence over segmented data
% This script plots figures based on data generated by script: ztrack_ramp_demo1.m
%
% Copyright 2018, David M. Halliday.
% This file is part of NeuroSpec.
%
%    NeuroSpec is free software; you can redistribute it and/or modify
%    it under the terms of the GNU General Public License as published by
%    the Free Software Foundation; either version 2 of the License, or
%    (at your option) any later version.
%
%    NeuroSpec is distributed in the hope that it will be useful,
%    but WITHOUT ANY WARRANTY; without even the implied warranty of
%    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%    GNU General Public License for more details.
%
%    You should have received a copy of the GNU General Public License
%    along with NeuroSpec; if not, write to the Free Software
%    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
%
%    NeuroSpec is available at:  http://www.neurospec.org/
%    Contact:  contact@neurospec.org
%
% Reference: Halliday DM, Brittain J-S, Stevenson CW, Mason R (2018)
%  Adaptive Spectral Tracking for Coherence Estimation: The z-tracker.
%  Journal of Neural Engineering, 15(2), 026004.
%  https://doi.org/10.1088/1741-2552/aaa3b4

% Plotting mean over specified range of frequencies
T_index=1;  % specify which segment size to use, here T=128

% Extract data
plot_dat=coh{T_index};
T=seg_size_all(T_index);
[np_freq np_seg np_q np_trials]=size(plot_dat);

% Number of trials to plot for each configuration (need even number for subplot)
np_trials_plot=10;

% Specify how many points to plot in each trial
switch tau
  case 20 
    plot_pts=2*tau*samp_rate+1; % For tau=20, 2 sets, 40 sec
    plot_sec=40;
  case 2  
    plot_pts=5*tau*samp_rate+1; % For tau=2,  5 sets, 10 sec
    plot_sec=10;
end   

% Different frequencies to include in mean
% (1:31) - average over first half of frequency spectrum for T=128
%    15  - single value using median frequency, no averaging
freq_mean_ind_all=[{(1:31)'} ; {15}];

% Scaling on plots
ch_max=1;

for ind_freq=1:length(freq_mean_ind_all)
  freq_mean_ind=freq_mean_ind_all{ind_freq};
  
  for ind_alpha=1:np_q
    figure

    for ind_trial=1:np_trials_plot;
      subplot(np_trials_plot/2,2,ind_trial)
      title_str=[Q_str_all{ind_alpha},', T: ',num2str(T),', Trial: ',num2str(ind_trial),', Freq: ',num2str(length(freq_mean_ind))];
      pspzt_ch1_target(plot_dat(:,:,ind_alpha,ind_trial),cl{T_index,ind_alpha}(ind_trial),ch_target{1,1},freq_mean_ind,ch_max,title_str)
      axis([0 plot_sec 0 ch_max]) % Scale x-axis
    end % ind_trial

  end % ind_alpha

end  % ind_freq
